#parameters:

services:
    app.webserverlog.filters_listener:
        class: AppBundle\WebServerLog\EventListener\FilterListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    app.webserverlog.command.collector_command:
        class: AppBundle\WebServerLog\Command\CollectorCommand
        arguments: ['@doctrine.orm.entity_manager', '@app.webserverlog.collector', '%kernel.logs_dir%']
        tags:
            - { name: console.command }

    app.webserverlog.collector:
        class: AppBundle\WebServerLog\Collector
        arguments: ['@doctrine.orm.entity_manager', '@app.webserverlog.reader', '@app.webserverlog.parser']

    app.webserverlog.reader:
        class: AppBundle\WebServerLog\Reader

    app.webserverlog.parser:
        class: Kassner\LogParser\LogParser

    app.webserverlog.normalizer:
        class: AppBundle\WebServerLog\Serializer\LogEntryNormalizer
        tags:
            - { name: serializer.normalizer }
